name: CI â€“ Tests + Coverage + Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project and test dependencies
        run: |
          pip install --upgrade pip
          pip install .[test]
          pip install pdoc

      - name: Run tests with coverage
        run: |
          pytest tests --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml


  docs:
    needs: tests
    runs-on: ubuntu-latest

    permissions:
      contents: write     # indispensable pour gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project and pdoc
        run: |
          pip install .
          pip install pdoc

      - name: Build documentation
        run: |
          mkdir -p docs/build
          pdoc --force --html --output-dir docs/build src

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
